[formatter.nix]
command = "nix"
options = ["fmt"]
includes = ["*.nix"]

[formatter.python]
command = "black"
includes = ["*.py"]

[global]
excludes = [
  "*.gitignore",
  "*.lock",
  ".editorconfig",
  "LICENSE.md",
]
