[formatter.md]
command = "mdformat"
options = [
  "--number",
  "--wrap=72",
]
includes = [
  "*.md",
]

[formatter.nix]
command = "nix"
options = ["fmt"]
includes = ["*.nix"]

[formatter.py]
command = "black"
options = [
  "--line-length=79",
]
includes = [
  "*.py",
]

[global]
excludes = [
  "*.gitignore",
  "*.lock",
  ".editorconfig",
  "LICENSE.md",
]
